# Copyright 2018 Ranjit Deshpande <ranjitdeshpande@hotmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

NAME		:= binutils
VERSION		:= 2.24
CONFIG_FLAGS	= --enable-shared --with-gmp=$(TARGET_DIR)/usr \
		   --with-mpfr=$(TARGET_DIR)/usr --with-mpc=$(TARGET_DIR)/usr \
		   --with-system-zlib --disable-werror
OBJDIR		:= __obj
CC		= cc

CPPFLAGS	= -I$(TARGET_DIR)/usr/include
LDFLAGS		= -L$(TARGET_DIR)/usr/lib

# Also, Tru64's ld does not like the archives generated by GNU ar.
# Therefore we delete GNU ar, ranlib, nm and strip
INSTALL_CUSTOM_CMDS = rm -f $(TARGET_DIR)/usr/bin/ar \
			$(TARGET_DIR)/usr/bin/nm \
			$(TARGET_DIR)/usr/bin/ranlib \
			$(TARGET_DIR)/usr/bin/strip \
			$(TARGET_DIR)/usr/alphaev56-dec-osf5.1b/bin/ar \
			$(TARGET_DIR)/usr/alphaev56-dec-osf5.1b/bin/nm \
			$(TARGET_DIR)/usr/alphaev56-dec-osf5.1b/bin/ranlib \
			$(TARGET_DIR)/usr/alphaev56-dec-osf5.1b/bin/strip

include makefiles/pkgbuild.mk
